from fpdf import FPDF


def create_pdf_report(title: str, user_email: str, summary_text: str) -> bytes:
    """PDF Report banakar uske bytes return karta hai."""
    pdf = FPDF()
    pdf.add_page()

    # Title Section
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "URBAN EYE AI - INCIDENT REPORT", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    # Incident Details
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Incident Title: {title}", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Reported By: {user_email}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Platform Status: Verified AI Detection", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Detection Summary & Details:", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, summary_text)

    pdf.ln(15)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(
        0,
        10,
        "This is an automated report generated by UrbanEye AI System.",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C",
    )

    # Return PDF as Bytes
    return bytes(pdf.output())
